git clone https://github.com/mounikavelma/SpringBoot_2.git
git clone https://github.com/mounikavelma/eureka-restclient.git
git clone https://github.com/mounikavelma/Spring.git
git clone https://github.com/mounikavelma/eureka-restserver.git
git clone https://github.com/mounikavelma/HibernateInterfaceMapping.git
git clone https://github.com/mounikavelma/HibernateMappings.git
git clone https://github.com/mounikavelma/SpringBoot.git
git clone https://github.com/mounikavelma/JUnitTest.git
git clone https://github.com/mounikavelma/MessengerApplication.git
git clone https://github.com/mounikavelma/StrutsProjectSample.git
git clone https://github.com/mounikavelma/microservices-demo.git
git clone https://github.com/mounikavelma/maven-project.git
